branches:
  only:
    - desktop
language: python
python:
  - 2.7
install: python setup.py install
before_script:
  - curl -k -L -O http://ftp.mozilla.org/pub/mozilla.org/b2g/nightly/latest-mozilla-b2g18/b2g-18.0.multi.linux-x86_64.tar.bz2
  - tar xvjf b2g-18.0.multi.linux-x86_64.tar.bz2
  - echo -e "user_pref('marionette.force-local', true);\n" >> b2g/gaia/profile/user.js
  - sh -e /etc/init.d/xvfb start
  - sleep 10
  - b2g/b2g > b2g.log &
  - sleep 60
script: gaiatest --address=localhost:2828 --type=b2g-antenna-bluetooth-carrier-camera-sdcard-wifi-xfail gaiatest/tests/manifest.ini
env:
  - DISPLAY=':99.0'
notifications:
  email:
    - webqa-ci@mozilla.org
  irc:
    - "irc.mozilla.org#automation"
    - "irc.mozilla.org#mozwebqa"
